// RenderVolume_HS.hlsl
//
// Light volume hull shader (quad patches, integer partitioning, CCW triangles).
// The control points are passed through. The patch constant function
//   1. culls the patch when, for every control point, the segment from the light's near point
//      (the frustum apex / the omni light position) to the control point lies completely
//      outside the view frustum (left/right/top/bottom or behind the near plane),
//   2. finds, per control point, the point of that segment closest to the eye,
//   3. sets every edge factor so that the edge, projected on screen, is cut into pieces of about
//      g_fTargetRaySize pixels (both for the closest points and the control points themselves,
//      the larger factor wins), clamped to [1, MAX_TESS_FACTOR],
//   4. (frustum only) forces factor 1 on edges lying on the frustum border, so the volume sides
//      generated by DrawFrustumCap match without cracks.
//
// Caller: ContextImp_D3D11::RenderVolume_DoVolume_Directional / _Spotlight / _Omni
//         (NvVolumetricLighting.d3d11.dll 0x18000A120 / 0x18000A8D0 / 0x18000B700)
// Table: hs_RenderVolume @ 0x1801FE050 (64 entries,
//        index = SHADOWMAPTYPE | CASCADECOUNT << 1 | VOLUMETYPE << 3 | MAXTESSFACTOR << 4).
// SHADOWMAPTYPE and CASCADECOUNT do not change the code (all 8 combinations are identical).

#include "ShaderCommon.hlsli"
#include "RenderVolumeGeom.hlsli"

#ifndef VOLUMETYPE
#define VOLUMETYPE VOLUMETYPE_FRUSTUM
#endif

#ifndef MAXTESSFACTOR
#define MAXTESSFACTOR MAXTESSFACTOR_LOW
#endif

#if (MAXTESSFACTOR == MAXTESSFACTOR_LOW)
#define MAX_TESS_FACTOR 16.0f
#elif (MAXTESSFACTOR == MAXTESSFACTOR_MEDIUM)
#define MAX_TESS_FACTOR 32.0f
#else
#define MAX_TESS_FACTOR 64.0f
#endif

// Point of the segment [vStart, vEnd] closest to the eye
float3 ClosestPointToEye(float3 vStart, float3 vEnd)
{
    float3 vToEye = g_vEyePosition - vStart;
    float3 vRay = vEnd - vStart;
    float fLength = length(vRay);
    float t = max(min(fLength, dot(vToEye, vRay) / fLength), 0);
    return vStart + (t / fLength) * vRay;
}

// Tessellation factor of the edge [vA, vB] (world space): projected edge length in pixels divided
// by the desired ray (slice) size.
float CalcTessFactor(float3 vA, float3 vB)
{
    float fEdgeLength = length(vB - vA);
    float fDistance = length(0.5f * (vA + vB) - g_vEyePosition);
    float fProjW = g_mProj[3][2] * fDistance + g_mProj[3][3];
    float fProjLength = fEdgeLength * g_mProj[1][1] / fProjW;
    return clamp(abs(fProjLength) * g_vOutputViewportSize.y / g_fTargetRaySize, 1.0f, MAX_TESS_FACTOR);
}

// Edge factor: the larger of the factors of the eye-closest points and of the control points
float CalcEdgeFactor(float3 vClosestA, float3 vClosestB, float3 vA, float3 vB)
{
    return max(CalcTessFactor(vClosestA, vClosestB), CalcTessFactor(vA, vB));
}

HS_POLYGONAL_CONSTANT_DATA_OUTPUT HS_PolygonalPatchConstant(
    const OutputPatch<HS_POLYGONAL_CONTROL_POINT_OUTPUT, 4> patch)
{
    HS_POLYGONAL_CONSTANT_DATA_OUTPUT output;

    // Cull the patch if every ray (light near point -> control point) is entirely outside the
    // view frustum. vNearPos: near end of the ray per control point (light position).
    float4 vNearPos[4];
    bool bVisible = false;
    [unroll]
    for (int i = 0; i < 4; ++i)
    {
        float4 vScreenFar = mul(g_mViewProj, patch[i].vWorldPos);
        vScreenFar.xyz *= 1.0f / vScreenFar.w;
#if (VOLUMETYPE == VOLUMETYPE_FRUSTUM)
        vNearPos[i] = mul(g_mLightToWorld, float4(patch[i].vClipPos.xy, 0, 1));
#else
        vNearPos[i] = float4(g_vLightPos, 1);
#endif
        float4 vScreenNear = mul(g_mViewProj, vNearPos[i]);
        vScreenNear.xyz *= 1.0f / vScreenNear.w;
        bool2 bAbove = (vScreenFar.xy > 1.0f) && (vScreenNear.xy > 1.0f);
        bool3 bBelow = (vScreenFar.xyz < float3(-1, -1, 0)) && (vScreenNear.xyz < float3(-1, -1, 0));
        bool2 bOutsideXY = bAbove || bBelow.xy;
        bVisible = bVisible || (any(!bOutsideXY) || !bBelow.z);
    }

    if (bVisible)
    {
        float3 vClosest[4];
        [unroll]
        for (int j = 0; j < 4; ++j)
            vClosest[j] = ClosestPointToEye(vNearPos[j].xyz / vNearPos[j].w, patch[j].vWorldPos.xyz);

        // Edges in SV_TessFactor order: u = 0 (3-0), v = 0 (0-1), u = 1 (1-2), v = 1 (2-3)
        float fEdge[4];
        [unroll]
        for (int e = 0; e < 4; ++e)
        {
            int a = (e + 3) % 4;
            int b = e;
            fEdge[e] = CalcEdgeFactor(vClosest[a], vClosest[b], patch[a].vWorldPos.xyz, patch[b].vWorldPos.xyz);
#if (VOLUMETYPE == VOLUMETYPE_FRUSTUM)
            // Edges on the frustum border keep factor 1 (watertight with the frustum sides)
            bool2 bInteriorA = abs(patch[a].vClipPos.xy) < 0.99951171875f;
            bool2 bInteriorB = abs(patch[b].vClipPos.xy) < 0.99951171875f;
            output.fEdges[e] = all(bInteriorA || bInteriorB) ? fEdge[e] : 1.0f;
#else
            output.fEdges[e] = fEdge[e];
#endif
        }
        output.fInside[0] = max(fEdge[1], fEdge[3]);
        output.fInside[1] = max(fEdge[0], fEdge[2]);
    }
    else
    {
        output.fEdges[0] = 0;
        output.fEdges[1] = 0;
        output.fEdges[2] = 0;
        output.fEdges[3] = 0;
        output.fInside[0] = 0;
        output.fInside[1] = 0;
    }

    [unroll]
    for (int k = 0; k < 4; ++k)
        output.fReserved[k] = 0;
    return output;
}

[domain("quad")]
[partitioning("integer")]
[outputtopology("triangle_ccw")]
[outputcontrolpoints(4)]
[patchconstantfunc("HS_PolygonalPatchConstant")]
[maxtessfactor(MAX_TESS_FACTOR)]
HS_POLYGONAL_CONTROL_POINT_OUTPUT main(InputPatch<VS_POLYGONAL_OUTPUT, 4> ip, uint id : SV_OutputControlPointID)
{
    HS_POLYGONAL_CONTROL_POINT_OUTPUT output;
    output.vWorldPos = ip[id].vWorldPos;
    output.vClipPos = ip[id].vClipPos;
    return output;
}
