#ifndef VXGISAMPLE_SHADERS_CONETRACING_CONETRACINGPRESET_HLSLI
#define VXGISAMPLE_SHADERS_CONETRACING_CONETRACINGPRESET_HLSLI

#define VXGI_CT_BUILTIN_CBV_SLOT 1

#define VXGI_CT_DEPTH_BUFFER_SRV_SLOT 0
#define VXGI_CT_NORMAL_BUFFER_SRV_SLOT 1
#define VXGI_CT_FLAT_NORMAL_BUFFER_SRV_SLOT 2
#define VXGI_CT_STENCIL_BUFFER_SRV_SLOT 3
#define VXGI_CT_PREV_DEPTH_BUFFER_SRV_SLOT 4
#define VXGI_CT_PREV_NORMAL_BUFFER_SRV_SLOT 5

#define VXGI_CT_TEXTURE_SRV_SLOT_0 6
#define VXGI_CT_TEXTURE_SRV_SLOT_1 7
#define VXGI_CT_TEXTURE_SRV_SLOT_2 8
#define VXGI_CT_TEXTURE_SRV_SLOT_3 9
#define VXGI_CT_TEXTURE_SRV_SLOT_4 10

#define VXGI_CT_COMMON_UAV_SLOT_0 0
#define VXGI_CT_COMMON_UAV_SLOT_1 1
#define VXGI_CT_COMMON_UAV_SLOT_2 2

#define VXGI_CT_SAMPLE_POSITIONS_UAV_SLOT  3
#define VXGI_CT_CONE_DIRECTIONS_UAV_SLOT 4
#define VXGI_CT_APPEND_COUNTERS_UAV_SLOT 5

#define VXGI_CT_POINT_SAMPLER_SLOT  0
#define VXGI_CT_LINEAR_BORDER_SAMPLER_SLOT 1
#define VXGI_CT_ENV_MAP_SAMPLER_SLOT 2

#endif /* VXGISAMPLE_SHADERS_CONETRACING_CONETRACINGPRESET_HLSLI */
